In [1]:
import tensorflow as tf

In [6]:
# 特殊矩阵初始化
## 2 * 3的空矩阵
mat0 = tf.constant([[0, 0, 0], [0, 0, 0]])
mat1 = tf.zeros([2, 3])
mat2 = tf.ones([3, 2])
mat3 = tf.fill([2, 3], 15)
with tf.Session() as sess:
    print(sess.run(mat0))
    print(sess.run(mat1))
    print(sess.run(mat2))
    print(sess.run(mat3))

[[0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[15 15 15]
 [15 15 15]]


In [9]:
import tensorflow as tf
mat1 = tf.constant([[2], [3], [4]])
# mat2的维度与mat1保持一致，并且值全部用0填充
mat2 = tf.zeros_like(mat1)
# 把0-2之间分成10份，会有11个端点
mat3 = tf.linspace(0.0, 2.0, 11)

# 产生随机数范围在-1~2之前的 2行3列的矩阵
mat4 = tf.random_uniform([2, 3], -1, 2 )
with tf.Session() as sess:
    print(sess.run(mat2))
    print(sess.run(mat3))
    print

[[0]
 [0]
 [0]]
[0.        0.2       0.4       0.6       0.8       1.        1.2
 1.4       1.6       1.8000001 2.       ]
