In [1]:
# 类比数据库的学习CRUD
import numpy as np
data1 = np.array([1, 2, 3, 4, 5])
print(data1)

[1 2 3 4 5]


In [2]:
data2 = np.array([[1, 2], 
                  [3, 4]])
print(data2)

[[1 2]
 [3 4]]


In [3]:
# 打印矩阵的维度
print(data1.shape)
print(data2.shape)

(5,)
(2, 2)


In [12]:
# 初始化一些特殊的矩阵
# zeros ones 
print(np.zeros((2, 3)))
print(np.ones((2, 2)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [13]:
# 改
data2[1, 0] = 5
print(data2)

[[1 2]
 [5 4]]


In [14]:
# 查
print(data2[1,1])

4


In [15]:
# 基本运算
data3 = np.ones([2, 3])
print(data3 * 2)

[[2. 2. 2.]
 [2. 2. 2.]]


In [16]:
print(data3 / 3)

[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]


In [17]:
print(data3+2)

[[3. 3. 3.]
 [3. 3. 3.]]


In [18]:
# 矩阵的加法和乘法
data4 = np.array([[1, 2, 3], [4, 5, 6]])

In [19]:
print(data3, data4)

[[1. 1. 1.]
 [1. 1. 1.]] [[1 2 3]
 [4 5 6]]


In [20]:
# 对应元素相加
print(data3 + data4)

[[2. 3. 4.]
 [5. 6. 7.]]


In [21]:
# 对应元素相乘
print(data3 * data4)

[[1. 2. 3.]
 [4. 5. 6.]]
